remote_theme: pages-themes/cayman
title: Personal Projects - Arian Torshizi
description: This website functions as a summary page for the github repository that can be found below. It contains 3 of my personal coding projects - OCR, Score Calculator, and TicTacToe.
plugins: 
- jekyll-remote-theme
